server:
  port: 9201
endpoints:
  shutdown:
    enabled: true
  restart:
    enabled: true
spring:
  config:
    name: selections
  application:
    name: selections
  cloud:
    config:
      enabled: true
      uri: http://localhost:8282
      failFast: true