server:
  port: 9002
spring:
  application:
    name:hystrixdashboard
  config:
    name:hystrixdashboard
security:
  ignored:true
turbine:
  aggregator:
    clusterConfig: selections
  appConfig: selections