info:
    component: zuul server app    
server:
    port: 8080  
spring:
    application:
        name: zuulserver
    cloud:
        config:
            enabled: true
            uri: http://localhost:8282